# This workflow will upload binaries as release artifacts to Codeberg Actions.
# Please note that only Linux binaries are uploaded. For Windows, please visit:
# https://multitoolplusplus.codeberg.page/wiki/wiki/installing-dependencies.html#windows
# https://multitoolplusplus.codeberg.page/wiki/wiki/building-multitool-with-cmake.html

# For macOS, please visit:
# https://codeberg.org/multitoolplusplus/app/fork # you're on your own

name: Upload binaries as release artifacts

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake curl build-essential gcc
        mkdir -p build # In case it somehow exists already
        cd build
        cmake ..
        cmake --build .
        cd .. # Go back to repository root, to prevent the next step failing

    - name: Upload binaries as action artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pre-compiled binaries
        path: build
